name: Post from RSS

env:
  LAST_RUNS_PATH: .last_runs.json

on:
  # schedule:
  #   - cron: '30 11 * * 2' # Every Tuesday at 11:30 UTC (12:30 GMT+1)
  workflow_dispatch:
    inputs:
      force_latest:
        description: Enter the number of recent feed entries to force re-post
        type: number
        default: 0


jobs:
  rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v6

      - name: Create venv and install dependencies
        run: uv sync

      - name: Run RSS to Social
        run: >
          uv run rss_to_social.py \
            --force-latest ${{ github.event.inputs.force_latest }}
        env:
          RSS_FEED_URLS: ${{ vars.RSS_FEED_URLS }}

      - name: Commit updated $LAST_RUNS_PATH if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $LAST_RUNS_PATH
          git diff --cached --quiet || git commit -m "Update $LAST_RUNS_PATH"
        continue-on-error: true

      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
