name: Post from RSS

on:
  # schedule:
  #   - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up uv and Python
        uses: actions/astral-sh-setup-uv@v6

      - name: Create venv and install dependencies
        run: uv sync

      - name: Run RSS to Social
        run: uv run rss_to_social.py
        env:
          RSS_FEED_URLS: ${{ vars.RSS_FEED_URLS }}

      # - name: Commit updated last-posted.txt if changed
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git add last-posted.txt
      #     git diff --cached --quiet || git commit -m "Update last-posted.txt"
      #   continue-on-error: true

      # - name: Push changes
      #   if: success()
      #   uses: ad-m/github-push-action@v0.8.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
